# Generated by Django 5.0.7 on 2024-08-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='bin',
            new_name='company_bin',
        ),
    ]
