# Generated by Django 5.0.7 on 2024-08-06 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_rename_bin_company_company_bin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kfc_name', models.CharField(max_length=512, verbose_name='КФС название')),
                ('kfc_code', models.IntegerField(verbose_name='КФС код')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='kfs',
        ),
        migrations.AddField(
            model_name='company',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_bin',
            field=models.CharField(max_length=12, unique=True, verbose_name='БИН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='kato',
            name='kato_code',
            field=models.IntegerField(verbose_name='КАТО коде'),
        ),
        migrations.AlterField(
            model_name='krp',
            name='krp_code',
            field=models.IntegerField(verbose_name='КРП код'),
        ),
        migrations.AlterField(
            model_name='kse',
            name='kse_code',
            field=models.IntegerField(verbose_name='КСЕ код'),
        ),
        migrations.AlterField(
            model_name='oked',
            name='oked_code',
            field=models.IntegerField(verbose_name='ОКЭД код'),
        ),
        migrations.CreateModel(
            name='GosZakupCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loader.company', verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='GosZakupSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loader.company', verbose_name='Организация')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='kfс',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='loader.kfc', verbose_name='КФС'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Nds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loader.company', verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loader.company', verbose_name='Организация')),
            ],
        ),
        migrations.DeleteModel(
            name='Kfs',
        ),
    ]
