# Generated by Django 5.0.7 on 2024-08-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0003_kfc_remove_company_kfs_company_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=128, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='kato',
            name='kato_code',
            field=models.IntegerField(unique=True, verbose_name='КАТО коде'),
        ),
        migrations.AlterField(
            model_name='kfc',
            name='kfc_code',
            field=models.IntegerField(unique=True, verbose_name='КФС код'),
        ),
        migrations.AlterField(
            model_name='krp',
            name='krp_code',
            field=models.IntegerField(unique=True, verbose_name='КРП код'),
        ),
        migrations.AlterField(
            model_name='kse',
            name='kse_code',
            field=models.IntegerField(unique=True, verbose_name='КСЕ код'),
        ),
        migrations.AlterField(
            model_name='oked',
            name='oked_code',
            field=models.IntegerField(unique=True, verbose_name='ОКЭД код'),
        ),
    ]
