# Generated by Django 5.0.7 on 2024-08-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0004_alter_company_email_alter_company_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='kfс',
            new_name='kfc',
        ),
    ]
