# Generated by Django 5.0.7 on 2024-08-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0006_alter_company_kato_alter_company_kfc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pay_nds',
            field=models.BooleanField(null=True, verbose_name='Плательщик НДС'),
        ),
        migrations.AlterField(
            model_name='company',
            name='register_date',
            field=models.DateField(null=True, verbose_name='Время создания организации'),
        ),
    ]
