# Generated by Django 5.0.7 on 2024-08-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0008_alter_company_tax_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_kz',
            field=models.CharField(max_length=1024, null=True, verbose_name='Адрес организации на казахском'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_ru',
            field=models.CharField(max_length=1024, null=True, verbose_name='Адрес организации на русском'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ceo',
            field=models.CharField(max_length=1024, null=True, verbose_name='Руководитель организации'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_kz',
            field=models.CharField(max_length=1024, null=True, verbose_name='Название организации на казахском'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_ru',
            field=models.CharField(max_length=1024, null=True, verbose_name='Название организации на русском'),
        ),
    ]
